# Generated by Django 4.2.20 on 2025-03-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigateDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigatedTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sensorID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.sensor')),
                ('ventilatedTime', models.DateTimeField()),
                ('irrigatedTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('sensorID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.sensor')),
                ('lowerTemp', models.FloatField()),
                ('upperTemp', models.FloatField()),
                ('lowerHumidity', models.FloatField()),
                ('upperHumidity', models.FloatField()),
                ('lowerLight', models.FloatField()),
                ('upperLight', models.FloatField()),
                ('lowerSoil', models.FloatField()),
                ('upperSoil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VentilateDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventilatedTime', models.TimeField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('password__regex', '.{8,}')), name='password_min_length_8'),
        ),
        migrations.AddField(
            model_name='irrigatedaily',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor'),
        ),
        migrations.AddConstraint(
            model_name='ventilatedaily',
            constraint=models.UniqueConstraint(fields=('sensorID', 'ventilatedTime'), name='primary_key_ventilate_daily'),
        ),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.CheckConstraint(check=models.Q(('lowerTemp__lt', models.F('upperTemp'))), name='check_lower_temp_lt_upper_temp'),
        ),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.CheckConstraint(check=models.Q(('lowerHumidity__lt', models.F('upperHumidity'))), name='check_lower_humidity_lt_upper_humidity'),
        ),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.CheckConstraint(check=models.Q(('lowerLight__lt', models.F('upperLight'))), name='check_lower_light_lt_upper_light'),
        ),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.CheckConstraint(check=models.Q(('lowerSoil__lt', models.F('upperSoil'))), name='check_lower_soil_lt_upper_soil'),
        ),
        migrations.AddConstraint(
            model_name='irrigatedaily',
            constraint=models.UniqueConstraint(fields=('sensorID', 'irrigatedTime'), name='primary_key_irrigate_daily'),
        ),
    ]
