# Generated by Django 4.2.20 on 2025-03-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigatedaily',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor', verbose_name='sensorID'),
        ),
        migrations.AlterField(
            model_name='ventilatedaily',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor', verbose_name='sensorID'),
        ),
    ]
