# Generated by Django 4.2.20 on 2025-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_schedule_irrigatedtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='irrigatedTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ventilatedTime',
            field=models.DateTimeField(),
        ),
    ]
