# Generated by Django 4.2.20 on 2025-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enviroment_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=50, unique=True)),
                ('state', models.BooleanField()),
            ],
        ),
    ]
