# Generated by Django 4.2.20 on 2025-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_device_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_state',
            name='manualMode',
            field=models.BooleanField(null=True),
        ),
    ]
