# Generated by Django 4.2.20 on 2025-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_device_state_manualmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_state',
            name='manualMode',
            field=models.BooleanField(default=True),
        ),
    ]
