# Generated by Django 4.2.20 on 2025-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_irrigatedaily_irrigatedtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventilatedaily',
            name='ventilatedTime',
        ),
        migrations.AddField(
            model_name='ventilatedaily',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ventilatedaily',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
