# Generated by Django 4.2.20 on 2025-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='irrigatedTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ventilatedTime',
            field=models.TimeField(),
        ),
    ]
