# Generated by Django 4.2.20 on 2025-03-19 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_schedule_irrigatedtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviroment_log',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light', models.FloatField()),
                ('soil', models.FloatField()),
            ],
        ),
    ]
