# Generated by Django 4.2.20 on 2025-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_device_state_manualmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigatedaily',
            name='irrigatedTime',
        ),
        migrations.AddField(
            model_name='irrigatedaily',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='irrigatedaily',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='irrigatedaily',
            constraint=models.CheckConstraint(check=models.Q(('startTime__lt', models.F('endTime'))), name='check_start_time_lt_end_time'),
        ),
    ]
